### PR TITLE
Feature/add rhel

### PR DESCRIPTION
**Pull request by rooprob**
Hi 
This PR adds support for RHEL.

I also added molecule testing, and made some of the features toggle switches.

Sorry it turned into a long commit, but I left the features chunked up for your review.

### CODE REVIEW

**Comment by rooprob** [comment]
Confirmed branch is ready for merge.

**Comment by mrlesmithjr** [comment]
@rooprob I appreciate the work here for sure. I need some time to look through this. I am not a fan of Molecule so I would prefer to keep that out. Personally I use [this](https://github.com/mrlesmithjr/vagrant-box-templates) for all of my role testing but I understand that is a personal preference. But I do really appreciate it.

Thanks!

**Comment by rooprob** [comment]
No problem! I wasn’t bowled over by some of the ways molecule does it. 

I’ll check out your other project. 

If you prefer I can chunk up into separate PRs. Just let me know.

**Comment by rooprob** [comment]
@mrlesmithjr Just checking back in. Other than testing, is there any other feedback. I’ll make some time this week.

**Comment by mrlesmithjr** [comment]
@rooprob Thanks for checking back. I would like to remove the Molecule related bits and split some of these changes into more specific PRs where it makes sense. Then we can get some of this merged this week. I really appreciate your work for sure!

**Pull request closed without merging**
